### ISSUE TITLE
add option to define strategy of handling alternates

### ISSUE THREAD

**Issue by xfyre** [danceconvention/dcnet-public#292]
there should be two options available:
- optimistic strategy (2 ALT + 1 YES) is better than (2 YES + 1 NO)
- pessimistic strategy (2 ALT + 1 YES) is worse than (2 YES + 1 NO)

**Comment by gregbo** [comment]
During the 1990s and 2000s, there were many WSDC events that used the relative placement algorithm for callbacks.  If you take a look at this rec.arts.dance thread from 1998, you will see an exchange between Mike Corbett and Trish Connery discussing this usage.  IMO, this is a fairer (based on Kenneth Arrow's research) means of determining callbacks than adding up the judges' marks.  It puts the callbacks and finals at the same level of fairness, in that regard.

https://groups.google.com/forum/#!topic/rec.arts.dance/0yloiFiPtqo/discussion

**Comment by gregbo** [comment]
This is an example of how it was done with ones (yeses) and twos (alternates) in the Open Jill, Open Jack, Advanced Jill, and Advanced Jack divisions at ALHC 2001:

https://web.archive.org/web/20011215061149/http://users.erols.com/crhutch/vs2/alhc01sc.html

I would also like to point out that instead of using multiple alternate values that differ by decimal points, just use successive ordinals (as would be used in finals).  The procedure is already documented and understood.  If the judges feel there are too many people in a qualifying round to give unique marks to all, they can stop after a given number.  However, this could lead to ties that the chief judge would need to break, which might be of concern to people who feel the chief judge should not be used unless absolutely necessary (that is, for a tie that can't be broken conventionally by any rank-ordered method).

Here is an example from the 2002 Virginia State Open.  Note the Jills and Jacks Open Classic Lindy Hop Preliminaries.  In each, there were 13 dancers.  The judges gave unique placements of 1 through 9, with the remaining dancers getting a 10.

https://web.archive.org/web/20030602121754/http://users.erols.com/crhutch/vs2/vsosc.html

At any rate, if you are going to offer options, in my opinion, you should carefully explain each one's pros and cons, with regards to Kenneth Arrow's fairness criteria.

**Comment by xfyre** [comment]
@gregbo Thanks for your comments, this is very valuable and much appreciated. The amount of information about preliminary rounds scoring is very little to none, so I have actually implemented algorithms according to the scarce information I was able to find.

Currently preliminary round scoring *is* based on relative placement actually, but placements are limited to 1-2.x-3; everything else works in exactly the same way.

I will carefully research those links and discussions you provided, thanks again!

**Comment by xfyre** [comment]
Since WSDC introduced a standard method for ranking alternates, this is no longer needed.

For the record, the system will support four different methods for scoring preliminary rounds:
- raw scores with ranking by vector norm (descending) - 'fair' calculation without any preferences
- callback/alternate/no (1/2.x/3) with ranking by vector norm (ascending) - leans towards 'pessimistic' alternates as the number of judges increases
- callback/alternate/no (1/2.x/3) with selection by majority and ranking by vector norm (ascending) - this method was a default previously - leans towards 'optimistic' alternates as the number of judges increases
- WSDC callbacks ranking by sum of pre-defined weights (descending)
