### ISSUE TITLE
eMail log

### ISSUE THREAD

**Issue by fcastigliego** [danceconvention/dcnet-public#322]
Save in a easy dump table all email sent from dance convention about the event.
suggested fileds:
UniqueID (if is helpful)
Date sent, 
IDEvent, 
Destination EMail, 
eMail body FullText (with object) 

a page where i can search by user email
this will help me to check text messages, manage undelivery situation, ...

(in future we can handle the Opened/Clicked email to have confirm of email receipt)

**Comment by xfyre** [comment]
This essentially means implementing a basic transactional email system. I'd like to avoid spending too much effort on infrastructure things like this - because there's too many systems out there that already do that much better.

Instead, I propose the following.

We already use SendGrid to send out emails. What we can do in addition is the following:

- provide an option for promoter to configure his own transactional email system to use (for example SendGrid, Mailgun, Amazon SES etc.)
- if this is configured, all event related email will be sent through this system instead of default SendGrid account that danceConvention.net is using

Then you can use your favorite transactional email system to track everything you need.

Does that work for you?

**Comment by fcastigliego** [comment]
Even if you use external system, you will never be sure that the email will be safely sent, and in case of problem you will never new what happened exaclty.
The only way to be sure is log locally to the dance convention system. Append a row in a simple log table is really easy to implement and show it in  page to see all email sento to a participant.

i really would like to avoid to manage external system, register on it, fight with settings, etc... i would like easily see what the user received.

proposal for future are just ideas, but the email log is important

**Comment by xfyre** [comment]
Discussed it elsewhere and agreed on using SendGrid (which already provides all mail logging features you need) instead.

Setup details will follow soon.

**Comment by xfyre** [comment]
Also I have added more verbose logging about actual actions with user signup and emails being sent to standard signup history.
